# -*- coding: utf-8 -*-
"""정예린_test1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A6ac_xoqpwpU3KUfdHaihVUbpa9bF-FY
"""

korean = 100
english = 80
math = 75

total = korean+english+math
average = (korean+english+math)/3

print("총점 :",total)
print("평균 : {0:0,.2f}".format(average))

